### ISSUE TITLE
Generating in the same namespace.

### ISSUE THREAD

**Issue by ryan961** [jmattheis/goverter#100]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described do not work.
- [x] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
Hello, may I ask how should goverter (v1.1.0) be configured under the same directory level? I'm still getting the `import cycle not allowed` error after configuring like below:

## converter.go
```go
package data

import (
	"time"

	"example/internal/biz"
)

type (
	// goverter:converter
	// goverter:output:file ./converter_gen.go
	// goverter:output:package :data
	// goverter:ignoreMissing
	// goverter:extend TimeToTime
	Converter interface {
		ConvertUser(*User) *biz.UserInfo
	}
)
...
```

```bash
➜  goverter gen ./internal/data
```
## converter_gen.go
```go
// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package data

import (
	biz "example/internal/biz"
	data "example/internal/data"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertBizUserInfo(source *biz.UserInfo) *data.User {
......
```

**~~data "example/internal/data"~~** is redundant.

I looked up the [issues](https://github.com/jmattheis/goverter/issues/88), but they all seem out of date.

**Comment by ryan961** [comment]
Thank you for reply. It is OK after just trying :)
```
package data

import (
	"time"

	"example/internal/biz"
)

type (
	// goverter:converter
	// goverter:output:file ./converter_gen.go
	// goverter:output:package example/internal/data:data
	// goverter:ignoreMissing
	// goverter:extend TimeToTime
	Converter interface {
		ConvertUser(*User) *biz.UserInfo
	}
)
...
```

**Comment by jmattheis** [comment]
Awesome, I've added an FAQ to the website including this question: https://goverter.jmattheis.de/#/faq
