### ISSUE TITLE
Support `any` type alias

### ISSUE THREAD

**Issue by pauhull** [jmattheis/goverter#110]
Take this code snippet:
```go
package example

import "fmt"

// goverter:converter
type Converter interface {
	// goverter:map Property Property | AnyToString
	AToB(A) B
}

func AnyToString(source any) string {
	return fmt.Sprint(source)
}

type A struct {
	Property interface{}
}

type B struct {
	Property string
}
```

Goverter will fail to generate with the following error message:
```
Error while creating converter method:
    func (example.Converter).AToB(example.A) example.B

| example.A
|
|      | interface{}
|      |
source.Property
target.Property
|      |
|      | string
|
| example.B

Error using method:
    func example.AnyToString(source any) string

Method source type mismatches with conversion source: any != interface{}
```

This is problematic since some APIs still use the `interface{}` type while the Go standard library now only uses the `any` type alias. This means that in some cases you have to write conversion methods that take `interface{}`s as arguments and wrap the corresponding standard library methods.

Fixing this would probably mean fully supporting type aliases. I don't know how complex the internal implementation for that would be, so maybe handling the special case for `any` would suffice as it's the most used type alias in Go.

**Comment by jmattheis** [comment]
Fixed in [v1.3.0](https://goverter.jmattheis.de/changelog).
