### ISSUE TITLE
Distinguish empty map types 

### ISSUE THREAD

**Issue by yxu1111** [jmattheis/goverter#126]
**Describe the bug**
A nil map is always converted to an empty map ({}) which sometimes could cause issues if the caller treats them differently

**To Reproduce**
pass in a member variable that is a map of value nil will return a map of value '{}'

**Expected behavior**
Ideally it should keep the original behavior - nil to nil and {} to {}

Thanks!

**Comment by jmattheis** [comment]
Thanks for the report, could you try out the `map-nil` branch and verify the problem is fixed for you?

- `go install github.com/jmattheis/goverter/cmd/goverter@map-nil`
- or `go run github.com/jmattheis/goverter/cmd/goverter@map-nil [pattern]`
- or `go get github.com/jmattheis/goverter@map-nil`

**Comment by yxu1111** [comment]
yes, it works great! Thank you for your in-time response and quick fix!

**Comment by jmattheis** [comment]
Released with [`v1.3.1`](https://goverter.jmattheis.de/changelog#v1-3-1).
