### ISSUE TITLE
Why are generated files marked as executable?

### ISSUE THREAD

**Issue by isinyaaa** [jmattheis/goverter#128]
**Have you read the project documentation?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
The executable bit is set high on every file/folder created by `goverter`. Why is that the case?

**Source code**
I just ran the [example on the getting-started guide](https://goverter.jmattheis.de/).

<img width="727" alt="image" src="https://github.com/jmattheis/goverter/assets/39812919/e6ffe1c5-e264-4b35-a331-86909dd6693b">

Note: I also confirmed this behaviour on the latest version.

**Errors**
Include errors that occur while you run goverter.

**Comment by jmattheis** [comment]
That's a bug. The generated file shouldn't be executable.

**Comment by isinyaaa** [comment]
thanks for the quick answer, I was browsing through the code and can patch it if you want

**Comment by jmattheis** [comment]
Ahh thanks, I've already created an PR for this (:. Would you like to test / review the changes? (https://github.com/jmattheis/goverter/pull/129)

**Comment by jmattheis** [comment]
Fixed in [v1.3.2](https://goverter.jmattheis.de/changelog#v1-3-2).
