### ISSUE TITLE
How do I avoid / handle compilation errors due to changes?

### ISSUE THREAD

**Issue by irieimperator** [jmattheis/goverter#130]
**Have you read the project documentation?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
Hi, thanks for this great package, it is extremely useful to avoid having to write annoying boilerplate! 🙂 

I currently have a kind of "chicken and egg problem" when using it: goverter only works if the code compiles successfully, right? 
I have initially run goverter and use the methods in the code.
Now I change certain types and also adapt the converter methods accordingly. 
Due to these changes the project has errors because it still uses the old types. 
So I would have to run goverter so that everything is correct and compiles again - but exactly that does not work because goverter does not run.

Have I not understood something fundamental?  How do you recommend resolving the conflict?
Thanks mate!

**Comment by jmattheis** [comment]
If you are defining the output:file in the same directory as the converter interface, then this guide lists two possibles fixes for compile errors: https://goverter.jmattheis.de/guide/output-same-package

If you have a different problem, then could you create a minimal example when something breaks with compile errors? Generally you can define the goverter build constraint to specifically exclude files from the goverter compilation but keep in mind that the not excluded files must compile on their own without the excluded files. See https://goverter.jmattheis.de/reference/build-constraint
