### ISSUE TITLE
Nested Protos types

### ISSUE THREAD

**Issue by rwalerow** [jmattheis/goverter#131]
**Have you read the project documentation?**

- [ x ] Yes, but it does not include related information regarding my question.
- [ - ] Yes, but the steps described do not work.
- [ - ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
How should I write converter for nested protos types

**Source code**
From those types:
```
type PerSeverityResponseData struct {
	TotalAmount int32
	Severities  []Severity
}

type Severity struct {
	Severity string
	Amount   int32
}
```
Into those protos type?
```
message Severity {
  string severity = 1;
  int32 amount = 2;
}

message PerSeverityResponse {
  int32 total = 1;
  repeated Severity severities = 2;
}
```

I've tried something like this but it didn't work

```
// goverter:converter
// goverter:output:file ./mappersGenerated.go
// goverter:output:package samepackage here
type Converter interface {

	// goverter:map TotalAmount Total
	// goverter:ignoreUnexported
	ByHighSeverityToProtobuf(*PerSeverityResponseData) *PerSeverityResponse
}

```

**Comment by jmattheis** [comment]
Does this help? https://goverter.jmattheis.de/guide/configure-nested

**Comment by rwalerow** [comment]
I've found the solution for this issue, but configure nested is not satisfactorily, since the example I provided is very simple, only one level nested. 
What if somebody has to deal with structure 3 or 4 levels deep? That would require a lot of configuration.
I've manged to solve my issue with `// goverter:ignoreUnexported` but on interface level
