### ISSUE TITLE
useZeroValueOnPointerInconsistency on a per-field basis

### ISSUE THREAD

**Issue by NinjaPerson24119** [jmattheis/goverter#137]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to use this for the majority of the fields on a model, but I want to ensure that just a few fields are actually NULL.

**Describe the solution you'd like**

Ability to switch this on/off for specific fields so I don't have to manually write an adapter for each.

**Describe alternatives you've considered**

**Comment by jmattheis** [comment]
`useZeroValueOnPointerInconsistency` only affects conversions that have a pointer mismatch. E.g.
```go
// goverter:converter
type Converter interface {
	// goverter:useZeroValueOnPointerInconsistency
	Convert(source Input) Output
}

type Input struct {
	Name *string
	Age  *int
}

type Output struct {
	Name *string
	Age  int
}
```
This means the setting only has an effect on the Age(*int) to Age(int) conversion. Without the setting this would be an error.

The Name(*string) to Name(*string) conversion stays the same regardless of the setting. Could you describe what you want to achieve (with an example)?

**Comment by NinjaPerson24119** [comment]
I use SQLC to generate my DB models from a database schema. If the database changes, I rely on `goverter` to auto-fix my adapters when I regenerate.

This means that if I want to use a flag like `useZeroValueOnPointerInconsistency`, It will cause runtime errors if I apply it to the entire model at once.

E.g. *ulid -> ulid would result in passing `''` (empty string) to the DB instead of `NULL`. 

But I may have a field that doesn't get written to the DB, that I want to avoid having to write a wrapper like
```
//goverter:converter
func MyConverter(T* t) T {
 var dummy T
  return dummy
}
```

So my options right now are:
- use `useZeroValueOnPointerInconsistency` and get runtime errors if the DB schema changes accidentally
- write manual wrappers

**Comment by jmattheis** [comment]
So you want to guard against future schema changes, so database fields are never *T -> T converted as they must be nullable? I feel like this functionality would only partly solve this problem, as it's still possible to just misconfigure an "useZeroValueOnPointerInconsistency flag" on a field.

I say this should be covered by tests and not via goverter errors. Without a changing schema, the field configuration for "useZeroValueOnPointerInconsistency" wouldn't make sense because of the explanation in my first comment.

**Comment by NinjaPerson24119** [comment]
Yes, that's the right idea. I know applying this flag to an entire model could cause problems, but it's still useful to define on individual fields.

The problem is that it's all or nothing.

Tests would help, but result in loss of time. Part of what makes goverter a huge time saver is that I want to assume the adapters are correct. Otherwise I'd write them manually.

**Comment by jmattheis** [comment]
Currently, I don't see this use-case in scope for Goverter. Goverter converts the types correctly, if the schema and target types are misconfigured then goverter shouldn't be responsible for notifying about this.
