### ISSUE TITLE
--help option is not handled correctly

### ISSUE THREAD

**Issue by nilskuhn** [jmattheis/goverter#144]
**Describe the bug**
When running goverters help command via flag `--help`, it prints out the following:
```shell
$ goverter --help             
Error: unknown command: --help
Usage:
...
```
The bad thing is, that its return code is non-zero.

**To Reproduce**
Run goverter with help command:
```shell
goverter --help
echo $?
```
Return code is 1.

**Expected behavior**
Goverter help message should be shown without an error message and the return code should be 0.

The bad thing about this is that there isn't even a `version` command, so no option to call goverter in a noop way to do an optional installation like this:
```shell
goverter -h >/dev/null 2>&1 || go install github.com/jmattheis/goverter/cmd/goverter@latest
```

**Comment by jmattheis** [comment]
Good catch, as a workaround you can use `command -v` to check if a command exists:
```bash
command -v goverter || go install github.com/jmattheis/goverter/cmd/goverter@latest
```

**Comment by nilskuhn** [comment]
thanks, wasn't aware of command shell builtin
