### ISSUE TITLE
It is possible to extend with goverter interface as a whole?

### ISSUE THREAD

**Issue by pavetok** [jmattheis/goverter#159]
**Have you read the project documentation?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
I have multiple converters in different packages. How can I reuse them?

**Source code**
```go
package foo

type Input1 struct {}
type Output1 struct {}

// goverter:converter
type Converter interface {
    Convert(Input1) Output1
}
```
```go
package bar

type Input2 struct {
    Name foo.Input1
}
type Output2 struct {
    Name foo.Output1
}

// goverter:converter
// goverter:extend foo:Converter
type Converter interface {
    Convert(Input2) Output2
}
```

**Comment by jmattheis** [comment]
When using https://goverter.jmattheis.de/guide/format#variables-to-assign-variable you could `goverter:extend` all variables from the other convertre via regex e.g. `goverter:extend otherpackage:.*`. But otherwise this is not easily possible.

**Comment by pavetok** [comment]
It works! Thanks for the great tool!
