### ISSUE TITLE
failed to load package "command-line-arguments"

### ISSUE THREAD

**Issue by conghuhu** [jmattheis/goverter#161]
**Have you read the project documentation?**

- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described do not work.
- [x] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
env: 
- go 1.18.10
- mac M3
- goverter 1.5.0

Error after running `goverter gen`

**Source code**
```
package outer_lite_packer

//go:generate goverter gen ./convert.go ./convert.gen.go

// goverter:converter
type Converter interface {
	// goverter:ignore Irrelevant
	Convert(source *groupV2.Dto) *gofeed_group.Dto
}
```

**Errors**
![image](https://github.com/user-attachments/assets/f2e44d43-ad6f-4213-acf3-5723f5bbe924)

**Comment by jmattheis** [comment]
Try specifying the package, not the file:
```
goverter gen ./
```
