### ISSUE TITLE
Hierarchically mapping two identical fields 

### ISSUE THREAD

**Issue by soerenschneider** [jmattheis/goverter#163]
**Have you read the project documentation?**

- [x] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
I'm trying to govert a struct that has two identical fields that need to be hierarchically mapped to two different target fields.

**Source code**
```
// goverter:converter
// goverter:extend TimeToTime
type Converter interface {
    ConvertQueueItem(source generated.GetQueueItemsRow) model.PlaybookQueueItem
}

## Input:

type GetQueueItemsRow struct {
	Playbook     Playbook
	Inventory    Inventory
	Repository   Repository
	Repository_2 Repository
}

type Playbook struct {
	ID          int64
	RepoID      int64
	FilePath    string
	DateUpdated *time.Time
}

type Inventory struct {
	ID     int64
	Name   string
	Path   string
	RepoID int64
}

type Repository struct {
	ID                   int64
	Name                 string
	RepoUrl              string
	Branch               string
	ContentType          string
	LastFetch            *time.Time
	LastScan             *time.Time
	PlaybookIncludeRegex *string
	PlaybookExcludeRegex *string
}

---

## Output

type PlaybookQueueItem struct {
	Playbook    *Playbook  `json:"playbook,omitempty"`
	Inventory   *Inventory `json:"inventory"`
}

type Playbook struct {
	ID          int64       `json:"id"`
	FilePath    string      `json:"file_path"`
	DateUpdated *time.Time  `json:"date_updated,omitempty"`
	Repository  *Repository `json:"repository,omitempty"`
}

type Inventory struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Path       string      `json:"path"`
	Repository *Repository `json:"repository,omitempty"`
}

type Repository struct {
	ID                   int64      `json:"id"`
	Name                 string     `json:"name"`
	RepoUrl              string     `json:"repo_url"`
	Branch               string     `json:"branch"`
	ContentType          string     `json:"content_type"`
	LastFetch            *time.Time `json:"last_fetch"`
	LastScan             *time.Time `json:"last_scan"`
	PlaybookIncludeRegex *string    `json:"playbook_include_regex"`
	PlaybookExcludeRegex *string    `json:"playbook_exclude_regex"`
}
```

**Errors**
I tried several combinations using map and [nested mapping](https://goverter.jmattheis.de/guide/configure-nested) but I didn't get it to work properly.

Is there an easier way to achieve this conversion using goverter? Thanks!

**Comment by jmattheis** [comment]
Could you be a little more specific with your example, which fields should be mapped to where?

**Comment by soerenschneider** [comment]
Thanks for the rapid reply!
Ah yeah sorry, I guess it wasn't that obvious. :^)

To successfully map from `GetQueueItemsRow` to `PlaybookQueueItem` I need to map

`GetQueueItemsRow.Playbook` -> `PlaybookQueueItem.Playbook`
`GetQueueItemsRow.Repository` -> `PlaybookQueueItem.Playbook.Repository`
`GetQueueItemsRow.Inventory` -> `PlaybookQueueItem.Inventory`
`GetQueueItemsRow.Repository_2` -> `PlaybookQueueItem.Inventory.Repository`

I hope that makes it clearer!

**Comment by jmattheis** [comment]
Yeah. You can use [`autoMap`](https://goverter.jmattheis.de/reference/autoMap) together with [`map . TARGET`](https://goverter.jmattheis.de/reference/map#map-dot-target) to achieve this. 

```go
// goverter:converter
// goverter:extend TimeToTime
type Converter interface {
	// goverter:map . Playbook
	// goverter:map . Inventory
	ConvertQueueItem(source generated.GetQueueItemsRow) model.PlaybookQueueItem

	// goverter:autoMap Playbook
	// goverter:map Repository Repository
	// above :map isn't needed, but makes it more obvious
	ConvertPlaybook(source generated.GetQueueItemsRow) model.Playbook

	// goverter:autoMap Inventory
	// goverter:map Repository_2 Repository
	ConvertInventory(source generated.GetQueueItemsRow) model.Inventory
}
```

**Comment by soerenschneider** [comment]
I guess I've tried a combination that looked similar, but I honestly can't say for sure.

Thanks for the help, I'll try it on Wednesday when I'll have access to a computer again and will close the issue if it works!

**Comment by soerenschneider** [comment]
Awesome, it works. Thanks for the help!
