### ISSUE TITLE
 when embedding objects, the goverter:ignore directive for state, sizeCache, and unknownFields does not take effect.

### ISSUE THREAD

**Issue by luchukun** [jmattheis/goverter#174]
when embedding objects, the goverter:ignore directive for state, sizeCache, and unknownFields does not take effect.

type Struct A {
  type Struct EmbededA {
      state, 
     sizeCache,
     unknownFields
  }
} 

**Expected behavior**
when i set goverter:ignoreUnexported setting, it should ignore A.EmbededA.State

**Comment by jmattheis** [comment]
Provide a full example with conversion interface. Adding `goverter:ignoreUnexported` to the conversion interface likely works, as it's then globally enabled.
