### ISSUE TITLE
slice  goverter:mapIdentity bug

### ISSUE THREAD

**Issue by fitan** [jmattheis/goverter#27]
**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/34503273/176849562-a2167d11-66fb-4d57-b9ef-172bc5249bab.png)

![image](https://user-images.githubusercontent.com/34503273/176849632-86d3065d-7ea8-4131-9b36-05aa577e8475.png)

**Expected behavior**

**Comment by jmattheis** [comment]
mapIdentity is only allowed on structs, you've to define it like this:
```go
// goverter:converter
type Converter interface {
    // goverter:mapIdentity Address
    ConvertPerson(source Person) APIPerson
    ConvertPersons(source []Person) []APIPerson
}
```

**Comment by fitan** [comment]
> mapIdentity只允许在结构上，你必须像这样定义它：
> 
> ```go
> // goverter:converter
> type Converter interface {
>     // goverter:mapIdentity Address
>     ConvertPerson(source Person) APIPerson
>     ConvertPersons(source []Person) []APIPerson
> }
> ```

I'm glad he made it. Thank you for your quick answer
