### ISSUE TITLE
Support Nested Goverter Interface Definition

### ISSUE THREAD

**Issue by Jiang-Le** [jmattheis/goverter#30]
i suggest goverter can support nested interface definition, so that we can assign function into different module.
it will be more clear definition.
```
type StructA struct {
	Value  string
	Target TargetA
}

type StructB struct {
	Value  string
	Target TargetB
}

type TargetA struct {
	TA string
}

type TargetB struct {
	TB string
}

// goverter:converter
type TargetConvertor interface {
	// goverter:map TA TB
	TargetAToTargetB(a TargetA) TargetB
}

// goverter:converter
type StructConvertor interface {
	TargetConvertor	
	StructAToStructB(a StructA) StructB
}
```

**Comment by jmattheis** [comment]
You want to have converters in different modules and then they should use methods from each other? This will be difficult to implement because goverter currently only generates the converter from one package and the generate path is supplied via cli flags.
