### ISSUE TITLE
How to avoid `go vet copylocks` warnings?

### ISSUE THREAD

**Issue by s-takehana** [jmattheis/goverter#39]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
A clear and concise description of what the question is. Include errors and go source files.

How to avoid `go vet copylocks` warnings?

e.g.

```go
// goverter:converter
type Converter interface {
	Convert(source []Input) []Output
}

// generated gRPC code
type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

type Output struct {
	Name string
}
```

```shell
goverter -ignoreUnexportedFields ./example/simple
```

`generated.go`
<img width="479" alt="image" src="https://user-images.githubusercontent.com/3423547/207224641-6ed27467-af0d-441c-b945-fb1329ab126e.png">
```
call of ***** copies lock value: ***** contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
```

I want to use pointer.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/3423547/207226252-50532468-aec9-4e97-b316-e60c509b4928.png">

**Comment by waltcow** [comment]
same issue here 
https://github.com/jmattheis/goverter/issues/37#issuecomment-1341904549

**Comment by s-takehana** [comment]
Thanks!
