### ISSUE TITLE
Converting struct with time.Time fields generate invalid converter

### ISSUE THREAD

**Issue by matdurand** [jmattheis/goverter#4]
**Describe the bug**
When generating a converter between two struct with `time.Time` fields, the generated converter doesn't compile.

**To Reproduce**
Here is the code to generate the issue
```go
//go:generate go run github.com/jmattheis/goverter/cmd/goverter github.com/jmattheis/goverter/example/simple
package simple

import "time"

// goverter:converter
type Converter interface {
	Convert(source []Input) []Output
}

type Input struct {
	Name     string
	Birthday time.Time
	Age      int
}

type Output struct {
	Name     string
	Birthday time.Time
	Age      int
}

```

**Expected behavior**
Since the source and destination types are both `time.Time`, I would expect a simple assignment to be done in the converter, but instead, I have a `timeLocationToTimeLocation` and `timeTimeToTimeTime` methods generated and trying to play with private fields of the time type.

**Comment by matdurand** [comment]
I was able to bypass the issue by registering a custom converter

```go
// goverter:converter
// goverter:extend TimeToTime
type Converter interface {
  ...
}

func TimeToTime(t time.Time) time.Time {
	return t
}
```

**Comment by matdurand** [comment]
But could it be possible to give an error instead of generating invalid code? Generated code cannot play with private fields anyway because the converter is not in the same package so is there cases where this kind of generated code would work?

**Comment by jmattheis** [comment]
Yeah, an error would be useful. Currently goverter treats the time.Time struct like every other struct. It tries to map exported fields and ignores private fields.

**Comment by matdurand** [comment]
Seems to me like it also tries to map private fields? Here is the generated converter for time.Time
```go
func (c *ConverterImpl) timeTimeToTimeTime(source time.Time) time.Time {
	var timeTime time.Time
	timeTime.wall = source.wall
	timeTime.ext = source.ext
	var pTimeLocation *time.Location
	if source.loc != nil {
		timeLocation := c.timeLocationToTimeLocation(*source.loc)
		pTimeLocation = &timeLocation
	}
	timeTime.loc = pTimeLocation
	return timeTime
}
```
We can see it tries to access `.wall`, `.ext` and `.loc` which are all private fields. Am I missing something?

**Comment by jmattheis** [comment]
goverter will now fail, if there are unexported fields:

https://github.com/jmattheis/goverter/blob/0b2e20a09b20ff4a9a35612b7795c44aaab71cf2/scenario/3_struct_unexported.yml#L20-L55

**Comment by matdurand** [comment]
It works great. Thanks!
