### ISSUE TITLE
[Questions] When generating converters, is it possible to generate constructor at the same time

### ISSUE THREAD

**Issue by shuqingzai** [jmattheis/goverter#45]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described do not work.
- [x] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
A clear and concise description of what the question is. Include errors and go source files.

```go
type ResourceConverterImpl struct{}

func NewResourceConverter() gen.ResourceConverter {
	return &ResourceConverterImpl{}
}

func (c *ResourceConverterImpl) ConvertModelToDomain(source *model.Resource) (*types.Resource, error) {
	var pTypesResource *types.Resource
	if source != nil {
		typesResource := c.modelResourceToTypesResource(*source)
		pTypesResource = &typesResource
	}
	return pTypesResource, nil
}
```

**It is a good choice for dependency injection or initialization declaration**

**Comment by shuqingzai** [comment]
1. Interface-oriented coding, only need to instantiate the interface
2. Life cycle management, if you implement the constructor manually, delete the interface later, and regenerate the conversion code, you also need to manually delete the constructor, which is easily forgotten

**Comment by jmattheis** [comment]
> Life cycle management, if you implement the constructor manually, delete the interface later, and regenerate the conversion code, you also need to manually delete the constructor, which is easily forgotten

I don't understand, if you delete the interface, then there is a compile error on the constructor function. What do you mean with "delete the interface later", the converter interface? If so, then regenerating the conversion code isn't possible because the interface is required for that.
