### ISSUE TITLE
[Questions] When generating files, is it possible to generate independent files for each struct ?

### ISSUE THREAD

**Issue by shuqingzai** [jmattheis/goverter#46]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described do not work.
- [x] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
A clear and concise description of what the question is. Include errors and go source files.

**Now it seems that all defined interface generation structures will be in the same file `generated/generated.go`, but if it is developed by multiple people, my partner and I will define different interface generators, which will easily cause Git conflicts. If each structure can be generated independently file that's great**

**Comment by jmattheis** [comment]
I don't understand your problem. Are the merge conflicts in the generated code? To solve these conflicts, you only have to rerun goverter. Additionally, it's recommended to not commit generated code, as it can easily get outdated.

You could put the generators into different packages and executed goverter for both packages.

**Comment by shuqingzai** [comment]
还有一个更严重的问题。 随着时间的推移，定义和转换的接口越来越多，生成的文件会很大，因为生成的struct会合并到一个文件中，代码不易阅读

**Comment by jmattheis** [comment]
Code readability is subjective, I mostly find it easy navigating through the single file because it's possible to navigate to the implementing method on the Converter interface.

I don't think it's worth the effort to change goverter to create separate files for the converter method implementations.

**Comment by jmattheis** [comment]
This feature was added in v1.0.0. See [`output:file`](https://goverter.jmattheis.de/reference/output)
