### ISSUE TITLE
Structure conversion error

### ISSUE THREAD

**Issue by shuqingzai** [jmattheis/goverter#52]
**Describe the bug**

**To Reproduce**
Include the input file that goverter has problems with, and describe the steps
you took to trigger the bug

**Expected behavior**

**time.go**

```go
import "github.com/golang-module/carbon/v2"

type In struct {
	CreatedAt  carbon.DateTime
	ReleasedAt *carbon.DateTime
}

type Out struct {
	CreatedAt  carbon.DateTime
	ReleasedAt *carbon.DateTime
}

// goverter:converter
type Converter interface {
	ModelToDomain(source *In) (*Out, error)
}
```

1.  If the unexported field is ignored, panic: runtime error: invalid memory address or nil pointer dereference
```bash
go run github.com/jmattheis/goverter/cmd/goverter --ignoreUnexportedFields --wrapErrors ./time.go
```

2. If unexported fields are not ignored, an error field mismatch will be reported
```bash
go run github.com/jmattheis/goverter/cmd/goverter  --wrapErrors ./time.go
```

**Comment by jmattheis** [comment]
Goverter doesn't know how to deeply clone `carbon.DateTime` so, you've to manually define the method. As far as I can see, carbon.DateTime is immutable and every call method call on it will return a new instance. Due to this, you can just pass the object through without doing any deep cloning, because you don't have to clone a value that is immutable.
```go
// goverter:converter
// goverter:extend CloneDateTime
type Converter interface {
	Convert(*In) *Out
}

type In struct {
	CreatedAt  carbon.DateTime
	ReleasedAt *carbon.DateTime
}

type Out struct {
	CreatedAt  carbon.DateTime
	ReleasedAt *carbon.DateTime
}

func CloneDateTime(source carbon.DateTime) carbon.DateTime {
	return source
}
```

**Comment by shuqingzai** [comment]
> 

Thinks
