### ISSUE TITLE
Is there a way to convert to code generate by protobuf oneof

### ISSUE THREAD

**Issue by gpoulin** [jmattheis/goverter#54]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
I'm trying to convert a pure Go struct to a struct generated using protobuf that include `oneof`. The generated code for `oneof` create an un-exported interface [ref](https://github.com/jmattheis/goverter/blob/d4c79e62e567d646f07d148fad972dd16152f196/builder/struct.go#L103) with multiple struct that implement the interface. I didn't find a way to use goverter to convert such a field. I tried using a custom Mapping Method but since the type is not exported by protobuf, it's not possible to define such method. One workaround to work with `oneof` is to create a type alias in the same module as the generated code. However, goverter match type based on there name [ref](https://github.com/jmattheis/goverter/blob/d4c79e62e567d646f07d148fad972dd16152f196/builder/struct.go#L103) so an alias wouldn't work. Is there a way that I missed to convert a struct that contains such a oneof?

**Comment by jmattheis** [comment]
Could you provide a minimal example which goverter cannot convert (input, output struct & goverter converter interface)?
