### ISSUE TITLE
@v0.17.1 report this error with go run :# github.com/jmattheis/goverter/xtype ../../../../pkg/mod/github.com/jmattheis/goverter@v0.17.1/xtype/type.go:279:11: t.TypeArgs undefined (type *types.Named has no field or method TypeArgs) make: *** [model_convert] Error 2

### ISSUE THREAD

**Issue by herac1es** [jmattheis/goverter#69]
**Describe the bug**

**To Reproduce**
Include the input file that goverter has problems with, and describe the steps
you took to trigger the bug

**Expected behavior**

**Comment by jmattheis** [comment]
Could you provide the files to reproduce this bug? Also describe how you've executed goverter.

**Comment by jmattheis** [comment]
It v0.17.1 goverter added support for generics, this increased the required go version for building goverter to go1.18. With goverter v0.17.2 the minimum go version for using goverter is go1.16.
