### ISSUE TITLE
TypeMismatch: Cannot convert interface{} to interface{}

### ISSUE THREAD

**Issue by JessedeJonge** [jmattheis/goverter#71]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
I have three layers: database, service and api

For the convertor from database -> service I am using the following custom function for json.RawMessages (empty by default JSONB columns):
```
func RawMessageToMapStringInterface(value json.RawMessage) map[string]interface{} {
	var res map[string]interface{}
	err := json.Unmarshal(value, &res)
	if err != nil {
		fmt.Println("Error unmarshal")
		return nil
	}
	return res
}
```

This fixes a panic `panic: unsupported type interface{}`

After that, I try to convert service layer to api layer but get error:

```
Error while creating converter method:
    func (/converter.ServiceToAPIConverter).ServiceToApi(source serviceStruct) apiStruct

|  service.User
|
|      | map[string]interface{}
|      |
|      |       | <mapvalue> interface{}
|      |       |
source.Settings[]
target.Settings[]
|      |       |
|      |       | <mapvalue> interface{}
|      |
|      | map[string]interface{}
|
| api.User

TypeMismatch: Cannot convert interface{} to interface{}
```

Any help ?

**Comment by jmattheis** [comment]
Goverter cannot know how to convert inteface{} to interface{} and thus fails. You must define the conversion method yourself. E.g.
```go
package example

// goverter:converter
// goverter:extend ConvertInterface
type Converter interface {
	Convert(source Input) Output
}

type Input struct {
	Age  interface{}
}

type Output struct {
	Age  interface{}
}

func ConvertInterface(value interface{}) interface{} {
    // convert value 
    converted := value
    return converted
}
```

**Comment by jmattheis** [comment]
Could you try out `v0.17.3`? It should be fixed there.
