### ISSUE TITLE
how can i convert differently named fields in struct.slices

### ISSUE THREAD

**Issue by lantegu** [jmattheis/goverter#84]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
A clear and concise description of what the question is. Include errors and go source files.
how can i convert Resources to Target, i tryed:
// goverter:map Id ID
or
// goverter: map ResourceItem.Id TargetItem.ID
but all of them are failed。
`type Resource struct {
    Items []*pkg1.ResourceItem
  }

type Target struct {
    Items []*pkg2.ResourceItem
}

package pkg1
  type ResourceItem struct {
      Id string
  }
package pkg2
  type TargetItem struct {
      ID string
  }
`

**Comment by jmattheis** [comment]
Post your `goverter:converter` interface declaration.
