### ISSUE TITLE
Could goverter ignore the nested fields?

### ISSUE THREAD

**Issue by h1z3y3** [jmattheis/goverter#85]
**Have you read the project readme?**

- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described do not work.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your question**
A clear and concise description of what the question is. Include errors and go source files.

My source: 
```
type Input struct {
  MetaData struct {
    Name string 
    Age int
  }
}

```

My target:
```
type Output struct {
  state int
  sizeCache int
  MetaData struct {
    state int
    sizeCache int
    Name string 
    Age int
  }
}
```

But `// goverter:ignore state sizeCache MetaData.state MetaData.sizeCache` only works for `.state` and `.sizeCache`

Error Message:
<img width="784" alt="image" src="https://github.com/jmattheis/goverter/assets/12080364/dec05a83-3cb0-447c-ae9a-dbd51dfc2043">

`// goverter:ignoreUnexported` also didn't work for me ;

**Comment by jmattheis** [comment]
`goverter:ignore` doesn't support nesting. You could define `goverter:ignoreUnexported` on the converter interface or define conversion method for the MetaData subtype and goverter:ignore the fields there too.
```go
// goverter:converter
type Converter interface {
	// goverter:ignore state sizeCache
	Convert(source Input) Output
	// goverter:ignore state sizeCache
	Converter(v struct{Name string; Age int}) MetaData
}

type Input struct {
	MetaData struct {
		Name string
		Age  int
	}
}

type Output struct {
	state     int
	sizeCache int
	MetaData  MetaData
}

type MetaData struct {
	state     int
	sizeCache int
	Name      string
	Age       int
}
```

**Comment by h1z3y3** [comment]
Thanks a lot! I've found the answer [here](https://goverter.jmattheis.de/#/conversion/configure-nested) ~
